/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MathOperations */

#ifndef _Included_MathOperations
#define _Included_MathOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MathOperations
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_MathOperations_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     MathOperations
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_MathOperations_subtract
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     MathOperations
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_MathOperations_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     MathOperations
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_MathOperations_divide
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     MathOperations
 * Method:    getLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MathOperations_getLibraryVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
