/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimpleMathCalculator */

#ifndef _Included_SimpleMathCalculator
#define _Included_SimpleMathCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SimpleMathCalculator
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_SimpleMathCalculator_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     SimpleMathCalculator
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_SimpleMathCalculator_subtract
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     SimpleMathCalculator
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_SimpleMathCalculator_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     SimpleMathCalculator
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_SimpleMathCalculator_divide
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
